#ifndef YKCLIENT_ERRORS_H
#define YKCLIENT_ERRORS_H

typedef enum
{
  /* Official yubikey client API errors. */
  YKCLIENT_OK = 0,
  YKCLIENT_BAD_OTP,
  YKCLIENT_REPLAYED_OTP,
  YKCLIENT_BAD_SIGNATURE,
  YKCLIENT_MISSING_PARAMETER,
  YKCLIENT_NO_SUCH_CLIENT,
  YKCLIENT_OPERATION_NOT_ALLOWED,
  YKCLIENT_BACKEND_ERROR,
  YKCLIENT_NOT_ENOUGH_ANSWERS,
  YKCLIENT_REPLAYED_REQUEST,
  /* Other implementation specific errors. */
  YKCLIENT_OUT_OF_MEMORY = 100,
  YKCLIENT_PARSE_ERROR,
  YKCLIENT_FORMAT_ERROR,
  YKCLIENT_CURL_INIT_ERROR,
  YKCLIENT_HMAC_ERROR,
  YKCLIENT_HEX_DECODE_ERROR,
  YKCLIENT_BASE64_DECODE_ERROR,
  YKCLIENT_BAD_SERVER_SIGNATURE,
  YKCLIENT_NOT_IMPLEMENTED,
  YKCLIENT_CURL_PERFORM_ERROR,
  YKCLIENT_BAD_INPUT,
  YKCLIENT_HANDLE_NOT_REINIT
} ykclient_rc;

#endif
